kind: Service
apiVersion: v1
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  selector:
    name: mongodb
  type: NodePort
  ports:
  - name: '27017'
    port: 27017
    targetPort: 27017
