apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: redis
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: user_name
      - name: SECRET_PASSWORD 
        valueFrom:
          secretKeyRef:
            name:  mysecret
            key: pass_word
  restartPolicy: Always