apiVersion: api/v1
kind: Deployment
metadata:
  name:  DEPLOYMENTNAME
  labels:
    name:  DEPLOYMENTNAME
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  DEPLOYMENTNAME
    spec:
      containers:
      - image:  IMAGENAME
        name:  DEPLOYMENTNAME
        resources:
          limits:
            cpu: "20m"
            memory: "55M"
        env:
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-password 
                key: db-password     
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - name: config
          mountPath: DESTINATION
        restartPolicy: Always
        imagePullPolicy: Always
      volumes:
      - name: SQL-CONFIG
        configMap:
          name: CONFIGMAPNAME
