apiVersion: api/v1
kind: Deployment
metadata:
  name:  DEPLOYMENTNAME
  labels:
    name:  DEPLOYMENTLABEL
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  CONTAINERLABEL
    spec:
      containers:
      - image:  IMAGENAME
        name:  DEPLOYMENTNAME
        resources:
          - requests:
              - limits:
                cpu: "20m"
                memory: "55M"
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always