- name: create users 
  hosts: node1 node2 
  become: true 
  tasks:
    - user:
        name: "{{ item }}"
        state: absent 
      loop:
        - joe 
        - matt 
        - james
        - oliver 
      when: ansible_os_family == "Debian"