apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb_database
  labels:
    name: redisdb_database
spec:
  selector:
    matchLabels:
      name: redisdb_database
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: redisdb_database
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redisdb_database
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 6379
