apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
spec:
  selector:
    matchLabels:
      name: web
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: muskrt/kubernetes-01-app:1.0
        imagePullPolicy: Always
        name: web
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 5000
