plugin: aws_ec2 
regions: 
  - "us-east-1"
keyed_groups:
  - key: tags.Name
    separator: "" 
compose:
  ansible_host: public_ip_address

boto_profile: default

# ansible-inventory --graph -i inventory_aws_ec2.yml