apiVersion: v1
kind: Secret
metadata:
  name:  result-server
stringData:
   MYSQL_DATABASE_HOST:  db.default.svc.cluster.local
   MYSQL_PASSWORD: toor1
   MYSQL_DATABASE: phonebook
   MYSQL_USER: mustafa
type: Opaque