version: "3"
services:
  web:
    build: . 
    restart: always
    volumes:
      - type: bind 
        source: ./
        target: /APP

  REDISDB:
    image: redis
    ports:
      - "89:89"

  MARIADB:
    image: mariadb
    ports:
      - "343:343"
