apiVersion: v1
kind: Secret
metadata:
  name: user-password
type: Opaque
data:
  db-password: dG9vcjE=
---

apiVersion: v1
kind: Secret
metadata:
  name: root-pass-word
type: Opaque
data:
  root-password: dG9vcg==

