- name: CONFIGURE FRONTEND NODE 
  hosts: FRONTEND  
  become : true 
  gather_facts: false 
  tasks: 
    - name: update the system 
      package: 
        name: "*"
        state : latest 
    - name: UNINSTALL DOCKER OLD VERSIONS 
      package: 
        name: "{{ item }}"
        state: absent 
      loop: 
        - docker 
        - docker-client 
        - docker-client-latest 
        - docker-common 
        - docker-latest 
        - docker-latest-logrotate 
        - docker-logrotate 
        - docker-engine
    - name: INSTALL YUM UTILS
      yum: 
        name: yum-utils
        state: latest 

    - name: ADD DOCKER REPO 
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    # - name: ADD DOCKER REPO 
    #   yum_manager:
    #     name: epel 
    #     baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    #     state: present
    - name: INSTALL DOCKER 
      yum: 
        name: "{{ item }}"
        state: latest 
      loop: 
        - docker-ce 
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: INSTALL PIP 
      package: 
        name: python3-pip
        state: latest 
    - name: 
      pip:
        name: docker 
        state: latest 
    - name: ADD EC2-USER TO DOCKER GROUP 
      user: 
        name: ec2-user 
        groups: docker 
        append: yes 

    # # - name: START DOCKER GROUP 
    # #   command: newgrp docker 

    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
    - name: START DOCKER SERVICE 
      systemd:
        name: docker 
        enabled: yes 
        state: started 
    - name: CREATE BUILD DIRECTORY 
      file:
        path: /home/ec2-user/FRONTEND
        state: directory 
        owner: root 
        group: root 
        mode: "0755"

    - name: COPY  FILES 
      copy:
        src: /home/mustafa/Desktop/aws-devops-projects/Devops/#####PROJECTS#####/ANSIBLE/App/frontend/
        dest: /home/ec2-user/FRONTEND

    - name: REMOVE CONTAINER IF EXISTS 
      shell: "docker ps -q --filter 'name=react_app' && docker stop react_app && docker rm -fv react_app && docker image rm -f react_app || echo 'not found'"

    - name: BUILD CONTAINER 
      docker_image: 
        name: react_app 
        build:
          path: /home/ec2-user/FRONTEND
        source: build 
        state: present 
    - name: CREATE POSTGRE DATABASE
      docker_container: 
        name: react_app 
        image: react_app 
        state: started 
        ports:
          - "3000:3000"
      register: container_info 
    - name: 
      debug:
        var: container_info 


    


