#!/usr/bin/python3
import os 
import sys

def create():
    file=open('ansible.cfg','w')
    file.write("test")
    file.close()
    print('success')
def delete():
    print('delete')

def main():
    file=open('temporary.txt','r')
    content=file.read()
    group_names=set()
    groups={}
    user_names={}

    for i in content.split('\n'):
        if len(i.split(' ')[0])>1:
            group_names.add(i.split(' ')[0])

    for i in group_names:
        groups[i]=[]
        user_name=input(f"Enter user name for {i} group:")
        user_names[i]=user_name

    for i in content.split('\n'):
        group_name=i.split(' ')[0]
        if len(group_name)>1:
            if group_name in group_names:
                # groups[group_name].append(i)
                
                i=i.split(' ')
                i=(i[0]+" ansible_host="+i[1]+f" ansible_user={user_names[group_name]}")
                groups[group_name].append(i)
    with open('inventory.txt','w') as file:
        for key in groups:
            file.write('['+key+']\n')
            for value in groups[key]:
                file.write(value+'\n')
        file.close()
    file.close()
    

   



if __name__=="__main__":
    main()
