kind: Service
apiVersion: v1
metadata:
  name: redis-database
  labels:
    name: redis-database
spec:
  selector:
    name: redis-database
  type: NodePort
  ports:
  - name: '6379'
    port: 6379
    targetPort: 6379
