AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  VPCID:
    Description: CHOOSE VPC
    Type: AWS::EC2::VPC::Id  
    
Resources:
  RDSSECURITYGROUP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ENABLES PORT 3306 FOR RDS
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: RDSSECGROUP
  MYRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 
      DBInstanceClass: 
      BackupRetentionPeriod: 
      DBInstanceIdentifier: 
      DBName: 
      DBParameterGroupName: 
      DBSecurityGroups: 
        - !Ref RDSSECURITYGROUP
      DBSnapshotIdentifier: 
      DBSubnetGroupName: 
      Engine: mysql
      EngineVersion: 8.0.025
      MasterUsername: 
      MasterUserPassword: 
      PubliclyAccessible: true
      VPCSecurityGroups:
        - vpc-sg-id
      Tags:
        - Key: Name
          Value: DATABASE
  
Outputs:

