version: "3"
services:
  web:
    image: web:3.0
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
  database:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
      
