version: "3"
services: 
  web:
    build: .
    restart: always
    depends_on:
      - redis 
      - mongodb 
    ports:
      - "5000:5000"
    
      
  mongodb:
    image: mongo 
    environment:
      MONGO_INITDB_DATABASE: flask_db
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

      
