#!/bin/bash 

#tfpac CREATE TESTDIR --PROVIDER=AWS 
#tfpac PACKAGE SRC_FOLDER_WITHOUT_TRAILING_SLASH DEST_PATH
#tfpac UNPACKAGE SRC_PATH DEST_PATH
#tfpac BUILD package_path dest_path 
if [ $UID -ne 0 ];
then 
    echo "please run as root"
fi 


files_to_create=(main.tf providers.tf outputs.tf $USER.auto.tfvars variable.tf)
 for index in $(seq 1 $#) ;
# for ((i=1;i<=4;i++));
do 
cmd="${!index}"
    if [ "$cmd" = "create" ]; 
    then 
        NEXT=`expr $index + 1`
        folder="${!NEXT}"
        mkdir -p $folder 
        for file in ${files_to_create[@]};
        do 
            touch  $folder/$file 
        done 

    elif [ "$cmd" = "package" ];
    then 
        NEXT=`expr $index + 1`
        src="${!NEXT}"
        
        NEXT=`expr $NEXT + 1`
        dst="${!NEXT}"
        
        file_name="$src.tar.gz"

        dst_path=${dst%%/}/$file_name

        tar cvzf $dst_path $src
    elif [ "$cmd" = "unpackage" ];
    then 
        NEXT=`expr $index + 1`
        src="${!NEXT}"

        tar -xzvf $src 
    elif [ "$cmd" = "build" ];
    then 
        echo test 
    elif [ "$cmd" = "--help" ];
    then 
        echo "Usage tfpac <command> <option src> <option dst>"
        echo "commands:"
        echo -e '\tcreate'
        echo -e '\t\t:example ->$ tfpac create test-project'
        echo -e '\tpackage'
        echo -e '\t\t:example ->$ tfpac package test-project .'
        echo -e '\tunpackage'
        echo -e '\t\t:example ->$ tfpac unpackage test-project .'
        echo -e '\tbuild'
        

    fi 

# NEXT=`expr $index + 1`
# echo "${!NEXT}"

done 
exit 


if [[ /home/$USER/.TFPAC ]]
then

    mkdir /home/$USER/.TFPAC 
else 
echo "test"
fi 





for file in ${files_to_create[@]};
do 
echo $file 
done 
exit 1

for var in "$@";
do  

if [[ ${#var} -gt 2 ]]
    then 
        echo TEST 
    else 
        echo $var 
    fi 


done


name=$1
IFS="="
read -ra ADDR<<<"$name" 
for i in "${ADDR[1]}";
do
echo "$i"
done