version: "3"
services:

  web:
    build: . 
    ports:
      - "80:5000"
    depends_on:
      - redis-db
      - postgre-db
    volumes:
      - type: bind
        source: ./
        target: /APP
  redis-db:
    image: redis  

  postgre-db:
    image: postgres


  