version: "3"
services:

  web:
    image: muskrt/kubernetes-04-bookworm_api
    restart: always
    environment:
      POSTGRES_USER: mustafa 
      POSTGRES_PASSWORD: toor1 
    ports:
      - "80:5000"
    depends_on:
      - redis-db
      - postgre-db
    volumes:
      - type: bind
        source: ./
        target: /APP
  redis-db:
    image: redis  

  postgre-db:
    image: postgres
    environment:
      POSTGRES_USER: mustafa 
      POSTGRES_PASSWORD: toor1
      POSTGRES_DB: bookworm_api_db

  