#!/bin/bash 

files_to_create=(main.tf providers.tf outputs.tf $USER.auto.tfvars variable.tf)
if [[ /home/$USER/.TFPAC ]]
then

    mkdir /home/$USER/.TFPAC 
else 
echo "test"
fi 



#TFPAC --CREATE=TESTDIR --PROVIDER=AWS 
#TFPAC -B package_path dest_path 
#TFPAC -PACKAGE SRC_PATH DEST_PATH

for file in ${files_to_create[@]};
do 
echo $file 
done 
exit 1

for var in "$@";
do  

if [[ ${#var} -gt 2 ]]
    then 
        echo TEST 
    else 
        echo $var 
    fi 


done


name=$1
IFS="="
read -ra ADDR<<<"$name" 
for i in "${ADDR[1]}";
do
echo "$i"
done


