AWSTemplateFormatVersion: 2010-09-09
Description: |
  THIS TEMPLATE IS WRITTEN FOR APPLICATION DEPLOYMENT ON AWS CLOUD WITH EC2 SERVICE 
  WITH SECURITY GROUP WHICH ALLOWS PORT 80 AND 22.
  
Parameters:

  VPCID:
    Description: CHOSE VPC
    Type: AWS::EC2::VPC::Id

  KEYNAME:
    Description: CHOSE KEYNAME
    Type: AWS::EC2::KeyPair::KeyName

  INSTANCETYPE:
    Description: CHOSE INSTANCETYPE
    Type: string 

  AMIID:
    Description: CHOSE AMIID
    Type: AWS::EC2::Image::Id

  
Resources:
  MYSERVERSECURITYGROUP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ENABLES SSH AND HTTP"
      SecurityGroupIngress:
        - IpProtocol: [tcp|udp|ip]
          FromPort: 
          ToPort: 
          CidrIp: --.--.--.--/--

        - IpProtocol: [tcp|udp|ip]
          FromPort: 
          ToPort: 
          CidrIp: --.--.--.--/--
      Tags:
        - Key: name
          Value: MYSERVERSECURITYGROUP
      VpcId: !Ref VPCID

  MYSERVER:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KEYNAME
      ImageId: !Ref AMIID 
      InstanceType: !Ref INSTANCETYPE
      SecurityGroupIds:
        - !Ref MYSERVERSECURITYGROUP
      UserData: !Base64 |
        #!/bin/bash 
        yum update -y 
        yum install subversion -y 
        svn export ....
        cd ....
        yum install amazon-linux-extras docker -y 
        usermod -a -G docker $USER
        newgrp docker 
        docker build -t myapp . 
        docker container run -dit  

      Tags:
        - Key: name
          Value: MYSERVER


Outputs: