apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb-database
  labels:
    name: redisdb-database
spec:
  selector:
    matchLabels:
      name: redisdb-database
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: redisdb-database
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redisdb-database
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
        ports:
        - containerPort: 6379
      restartPolicy: Always
