version: '3'
services:

  mongodb: 
    image: mongo 
  mongoapi:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
  