apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-password 
                  key: db-password
            - name: MARIADB_ROOT_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: db-config
          image: mariadb
          name: mariadb-test
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
