apiVersion: v1
kind: Pod
metadata:
  name: "MYAPP"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: MYAPP
    image: web
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 150Mi

    ports:
    - containerPort:  80
      name:  http


  restartPolicy: Always