apiVersion: v1
kind: Pod
metadata:
  name: podtest
  namespace: default
  labels:
    app: podtest
spec:
  containers:
  - name: podttest
    image: web:1.6
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 150Mi

    ports:
    - containerPort:  5000


  restartPolicy: Always