AWSTemplateFormatVersion: 2010-09-09
Description: |
  This templates creates a security group with instance with type t2.micro
  and ami-0b5eea76982371e91 which enables apache server on port 80 
Parameters:
  keyName:
    Description: keyname to connect ec2
    Type: AWS::EC2::KeyPair::KeyName
    Default: xxxxxxxx
Resources:
  romannumbers:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-050f61b1a47bfb02c
      GroupDescription: "enables ssh and http to ec server" # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: "Name"
          Value: "roman-numbers-secgrb"
  webserverhost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0b5eea76982371e91"
      InstanceType: "t2.micro"
      KeyName: !Ref keyName
      SecurityGroupIds:
        - !Ref romannumbers
      Tags:
        - Key: "Name"
          Value: "roman-numbers"
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3 -y
        yum install subversion -y 
        pip3 install flask 
        cd /home/ec2-user/
        svn export https://github.com/muskrt/aws-devops-projects.git/trunk/AWS/PROJECTS/ROMAN-NUMBERS-APPLICATION
        cd ROMAN-NUMBERS-APPLICATION/
        python3 app.py

Outputs:
  websiteurl:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt webserverhost.PublicDnsName

