version: "3"
services:
  web:
    build: . 
    restart: always
    depends_on:
      - mysql-database
    ports:
      - "80:80"
  mysql-database:
    image: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER : mustafa
      MYSQL_PASSWORD : toor1
      MYSQL_DATABASE : bookstore_db
    ports:
      - "3306:3306"



