version: "3"
services:
  db:
    image: mysql 
    environment:
      - MYSQL_ROOT_PASSWORD: toor 
    ports:
      - "3306:3306"


  web:
    build: . 
    restart: always
    ports:
      - 80:5000


