version: "3"
services:
  db:
    image: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE_HOST : 'database'
      DATABASE_USER : 'mustafa'
      DATABASE_PASSWORD : 'toor1'
      DATABASE_DB : 'bookstore_db'
    ports:
      - "3306:3306"
  web:
    build: . 
    restart: always
    ports:
      - 80:5000


