- name: DB CONFIGURATION
  hosts: DB_SERVER
  gather_facts: false 
  tasks:
    - name: UPDATE 
      become: yes 
      yum: 
        name: "*"
        state: latest
    - name: INSTALL MARIADB  PYTHON3 PIP
      become: yes 
      yum: 
        name: 
          - mariadb-server
          - python3
          - pip
        state: latest
        
    - name: INSTALL PYMYSQL
      pip:
        name: 
          - PyMySQL
        state: latest

    - name: START MARIADB
      become: yes 
      command: systemctl start mariadb
    - name: ENABLE MARIADB 
      become: yes 
      systemd: 
        name: mariadb 
        enabled: true 

