version: "3"
services:
  web:
    build: . 
    restart: always
    depends_on:
      - REDISDB
      - MARIADB
    # network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - type: bind 
        source: ./
        target: /APP

  REDISDB:
    image: redis:alpine
    ports:
      - "6379:6379"

  MARIADB:
    image: mariadb:10.5

    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: mustafa 
      MARIADB_PASSWORD: toor1
      MARIADB_DATABASE: abc_company
    volumes:
      - type: bind 
        source: ./mariadb/
        target: /docker-entrypoint-initdb.d/
        # - ./docker/mysql/data:/var/lib/mysql:rw
      # - ./mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql:rw

      - type: bind 
        source: ./mariadb/dbconfig.cnf
        target: /etc/mysql/conf.d/dbconfig.cnf
    ports:
      - "3306:3306"

